apiVersion: v1
kind: Service
metadata:
  name: authorisationservice-service
spec:
  type: ClusterIP
  selector:
    app: authorisationservice
  ports:
    - protocol: TCP
      port: 9094
      targetPort: 80