apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
spec:
  selector:
    matchLabels:
      app: mssql
  serviceName: "mssql"
  replicas: 2
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_SA_PASSWORD
              value: "uhohst1nky!"
            - name: ACCEPT_EULA
              value: "Y"
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
          volumeMounts:
            - name: mssql-storage
              mountPath: /var/opt/mssql
          livenessProbe:
            exec:
              command:
                - /opt/mssql-tools/bin/sqlcmd
                - -S
                - "localhost"
                - -U
                - "sa"
                - -P
                - "uhohst1nky!"
                - -Q
                - "SELECT 1"
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - /opt/mssql-tools/bin/sqlcmd
                - -S
                - "localhost"
                - -U
                - "sa"
                - -P
                - "uhohst1nky!"
                - -Q
                - "SELECT 1"
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 5
  volumeClaimTemplates:
    - metadata:
        name: mssql-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi