apiVersion: v1
kind: Service
metadata:
  name: seq-service
spec:
  selector:
    app: seq
  ports:
    - protocol: TCP
      port: 5341
      targetPort: 5341
      name: http
    - protocol: TCP
      port: 80
      targetPort: 5341
      name: http-alt