apiVersion: v1
kind: Service
metadata:
  name: seq-service
spec:
  type: LoadBalancer
  selector:
    app: seq
  ports:
    - protocol: TCP
      port: 5341
      targetPort: 5341
    - protocol: TCP
      port: 80
      targetPort: 80