apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-storage-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin-storage
  template:
    metadata:
      labels:
        app: zipkin-storage
    spec:
      containers:
        - name: zipkin-storage
          image: mariadb:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"
            - name: MYSQL_DATABASE
              value: "zipkin"
            - name: MYSQL_USER
              value: "zipkin"
            - name: MYSQL_PASSWORD
              value: "zipkinpassword"
          volumeMounts:
            - name: zipkin-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: zipkin-storage
          persistentVolumeClaim:
            claimName: zipkin-storage-pvc